services:
  - type: web
    name: arsidet
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements-deploy.txt
    startCommand: streamlit run main.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: OPENAI_API_KEY
        sync: false
