[theme]
primaryColor = "#16a085"
backgroundColor = "#f0f0f0"
secondaryBackgroundColor = "#ffffff"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
enableCORS = false
port = 8501
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[runner]
fastReruns = true
